### ISSUE TITLE
MVP Feedback TODO

### ISSUE THREAD

**Issue by torch2424** [torch2424/wasmer-examples#5]
# Mark and Nick Feedback

* [x] Add links to relevant technologies (WebAssembly.sh, WAPM, WasiEnv, wasm-pack, etc...)
* [x] [Remove any lingering notion -> markdown errors]( https://docs.wasmer.io/runtime/cli/runtime-cli-installation)?
* [x] Implement Notion comments from ( @MarkMcCaskey and @nlewycky  ) 😄 
* [x] Update image URLs inside markdown docs, from transferring from notion

# Syrus Feedback

* [x] [Add the edit this page](https://docusaurus.io/docs/en/site-config#editurl-string)
* [x] Double check that we link to the actual example directory in the examples, so people can view the end-to-end example project (#6 , @syrusakbary comment to double check on this)
* [x] ~~[Searching feature](https://docusaurus.io/docs/en/search) Applied, will Take a few days before [DocSearch](https://community.algolia.com/docsearch/) gets back to us and we can integrate~~ Moved to #11 

# Brandon Feedback

* [x] Smaller brand font in top left (As in the word documentation is unbolded)
* [x] Add icons or images to introduction
* [x] Multiple sections to break up wall of text
* [x] Home button may be removed (since left nav brand link to same)
* [x] Provide links like (to introduction.html) this to each section (WasmerJS, etc): https://www.twilio.com/docs

# Ivan Feedback

* [x] Could we add links to previous and next section at the bottom of the pages? That is useful to avoid scrolling to the menu, opening it, scrolling and clicking on the next section.
* [x] ~~The header takes too much space though, can we shrink it?~~ Moved to #12
